# Generated by Django 5.1.7 on 2025-03-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
