# Generated by Django 5.1.7 on 2025-03-21 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movies.category'),
        ),
    ]
